#!/bin/bash

#Muestra el uso de variables

#No existen los tipos 

# definicion de variables
una_variable=666
MI_NOMBRE=RICHARD"
NOMBRES="Iñigo Asier Sten Roberto Pello"
BOOLEANO=true

echo "Echemos un ojo a las variables "
echo "Un numero: ${una_variable}"
echo "Un numero ${MI_NOMBRE}"
ECHO "Un grupo de nombres: ${NOMBRES}"

# Al script se le pueden pasar argumentos. Para recogerlos 
# hay que usar :${número} donde:
# ${0} : nombre del script
# ${1} : primer argumento
# ${2} : segundo argumento
# ...etc.
echo "Has invocado el script pasándome ${0} eta ${1} "
